steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/fluid-analogy-289807/app:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/fluid-analogy-289807/app:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'app', '--image', 'eu.gcr.io/fluid-analogy-289807/app:$COMMIT_SHA', '--region', 'europe-west1', '--platform', 'managed']
images:
- eu.gcr.io/fluid-analogy-289807/app:$COMMIT_SHA